[build]
  publish = "public"
  functions = "netlify/functions"

# Pipedrive (proxy)
[[redirects]]
  from = "/api/pipedrive"
  to = "/.netlify/functions/pipedrive"
  status = 200
  force = true

# Notion: catálogos
[[redirects]]
  from = "/api/notion-tags"
  to = "/.netlify/functions/notion-tags"
  status = 200
  force = true

# Notion: plantillas
[[redirects]]
  from = "/api/notion-templates"
  to = "/.netlify/functions/notion-templates"
  status = 200
  force = true
