[build]
  publish = "public"
  functions = "netlify/functions"

# Pipedrive
[[redirects]]
  from = "/api/pipedrive"
  to = "/.netlify/functions/pipedrive"
  status = 200
  force = true

# Repo de plantillas
[[redirects]]
  from = "/api/templates-list"
  to = "/.netlify/functions/templates-list"
  status = 200
  force = true

[[redirects]]
  from = "/api/templates-upsert"
  to = "/.netlify/functions/templates-upsert"
  status = 200
  force = true

[[redirects]]
  from = "/api/templates-delete"
  to = "/.netlify/functions/templates-delete"
  status = 200
  force = true

[[redirects]]
  from = "/api/templates-import"
  to = "/.netlify/functions/templates-import"
  status = 200
  force = true

[[redirects]]
  from = "/api/templates-export.csv"
  to = "/.netlify/functions/templates-export"
  status = 200
  force = true
